---
title: "Cálculo Diferencial: Ejercicios de Derivadas (Primera Parte)"
author: "Carlos Ernesto Martinez"
date: "28 de Septiembre de 2023"
documentclass: article
output:
  pdf_document:
    toc: no  # Cambiado a "no" para eliminar la tabla de contenidos
    number_sections: no
header-includes:
  - \usepackage{multicol}
  - \usepackage{fancyhdr}
  - \usepackage[document]{ragged2e}
  - \pagestyle{fancy}
  - \fancyhf{}
  - \fancyfoot[C]{\thepage}
  - \fancyfoot[L]{\ifodd\value{page}\textit{\small Ejercicios de Límites (Primera Parte)}\else\textit{\small Carlos E Martínez-Rodríguez}\fi}
  - \fancyfoot[R]{\ifodd\value{page}\textit{\small Carlos E Martínez-Rodríguez}\else\textit{\small Ejercicios de Límites (Primera Parte)}\fi}
  - \usepackage[left=2cm,right=2cm,top=2cm,bottom=2cm]{geometry}
  - \fancyhead[LE,RO]{\nouppercase{\rightmark}}
  - \fancyhead[LO,RE]{\nouppercase{\leftmark}}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

\begin{enumerate}

\item Calcula las siguientes derivadas utilizando la definición de límite:

\begin{enumerate}
\begin{multicols}{3}
\item $f(x) = 2x + 3$
\item $f(x) = x^2 - 4x + 5$
\item $f(x) = 3x^2 + 6x + 2$
\item $f(x) = \frac{3}{x + 2}$
\item $f(x) = \frac{1}{x - 1}$
\item $f(x) = \frac{2}{x - 3}$
\item $f(x) = -x^2 + 3x - 1$
\item $f(x) = \sqrt{x + 1}$
\item $f(x) = \sqrt{4x - 7}$
\item  $f(x) = \frac{ 4}{\sqrt{x + 4}}$
\item $f(x) = \frac{- 1}{\sqrt{x + 2}}$
\item $f(x) = \sqrt{3x - 1}$
\end{multicols}
\end{enumerate}

\item Calcula la recta tangente a la función en el punto dado

\begin{enumerate}
\begin{multicols}{2}
\item $y= 4-x^{2}$, $P=\left(1,3\right)$
\item $y= x^{2}+1$, $P=\left(1,2\right)$
\item $y= 4x^{2}+2x$, $P=\left(2,20\right)$
\item $y= x^{2}-6x$, $P=\left(3,0\right)$
\end{multicols}
\end{enumerate}

\item Determine la pendiente de la recta tangente a la gráfica en el punto $(x_1,f(x_1))$
\begin{enumerate}
\begin{multicols}{3}
\item $f(x) = 2x^2-12x+1$
\item $f(x) = 7-3x+x^2$
\item $f(x) = 3x^3 + 2x^2-6x + 2$
\item $f(x) = \frac{2}{\sqrt{x}}$
\item $f(x) = \sqrt{4-2x}$
\item $f(x) = \frac{4}{3x^2}$
\end{multicols}
\end{enumerate}

\item Calcule las siguientes derivadas

\begin{enumerate}
\begin{multicols}{2}
\item $f(x) = 3x^5-3x^2+4x-1$
\item $f(x) = 2x^7+4x^6-3x^5+2x^4-8x^3+9x^2$
\item $f(x) = 4x^8+6x^6-4x^4+2x^2-x+10$
\item $f(x) = (2x^3-6x^2)(5x^4+2x^3)$
\item $f(x) = \frac{1}{6}x^6-x^5$
\item $f(x) = \frac{1}{4}x^4-\frac{1}{2}x^2$
\end{multicols}
\end{enumerate}

\item Calcule las siguientes derivadas

\begin{enumerate}
\begin{multicols}{3}
\item $f(x) = (3x^2 - 2x)(4x^3 + 5x^2)$

\item $g(x) = (2x^4 - 7x^3)(x^2 + 3x)$

\item $h(x) = (6x^3 + 4x^2)(2x^5 - x^4)$

\item $k(x) = (x^4 - 3x^3)(3x^2 + 2x)$
\item $m(x) = (4x^2 + 5x)(2x^3 - 6x^2)$
\end{multicols}
\end{enumerate}

\item Calcule las siguientes derivadas

\begin{enumerate}
\begin{multicols}{3}
\item $g(x) = \frac{1}{3}x^6 - \frac{1}{2}x^3$
\item $h(x) = \frac{1}{4}x^4 - 2x^2$
\item $k(x) = \frac{1}{9}x^9 - \frac{1}{2}x^7$
\item $m(x) = \frac{1}{6}x^6 - \frac{1}{4}x^4$
\item $n(x) = -\frac{1}{5}x^5 + \frac{1}{7}x^3$
\item $p(x) = \frac{1}{10}x^{10} - \frac{1}{3}x^3$
\end{multicols}
\end{enumerate}


\item Calcule las siguientes derivadas

\begin{enumerate}
\begin{multicols}{3}
\item $g(x) = \frac{1}{4}x^5 + \frac{1}{2}x^2$
\item $h(x) = \frac{3}{4}x^7 - \frac{1}{3}x^8$
\item $k(x) = \frac{1}{6}x^3 + \frac{1}{2}x^3$
\item $m(x) = \frac{1}{8}x^9 + \frac{1}{4}x^5$
\item $n(x) = -\frac{1}{2}x^2 - \frac{2}{3}x^6$
\item $p(x) = \frac{1}{2}x^4 - 3x^7$
\end{multicols}
\end{enumerate}

\item Calcule las siguientes derivadas

\begin{enumerate}
\begin{multicols}{3}
\item $g(x) = x^2 - 2x + \frac{1}{x^3}$

\item $h(x) = x^2 -\frac{3}{x} + \frac{1}{x^5}$

\item $k(x) = x^2 + \frac{2}{x} - \frac{1}{x^3}$

\item $m(x) = x^2 - \frac{4}{x} - \frac{1}{x^5}$

\item $n(x) = x^2 + \sqrt{3}x + \frac{1}{x^4}$

\item $p(x) = x^2 + 3x + \frac{1}{x^2}$
\end{multicols}
\end{enumerate}

\item Calcule las siguientes derivadas

\begin{enumerate}
\begin{multicols}{3}
\item  $g(x) = \frac{x^3}{3} - \frac{1}{x^3}$

\item $h(x) = -\frac{x^2}{3} + \frac{3}{x^2}$

\item $k(x) = \frac{x^5}{3} - \frac{2}{x^5}$

\item $m(x) = \frac{x^6}{3} - \frac{4}{x^6}$

\item $n(x) = -\frac{x^8}{3} + \frac{1}{x^8}$

\item $p(x) = \frac{x^4}{3} - \frac{7}{2x^4}$
\end{multicols}
\end{enumerate}

\item Calcule las siguientes derivadas

\begin{enumerate}
\begin{multicols}{3}

\item $g(x) = \frac{1}{x^2} + \frac{2}{3x^4}$

\item $h(x) = \frac{4}{x^4} + \frac{1}{4x^5}$

\item $k(x) = -\frac{2}{x^3} - \frac{3}{3x^8}$

\item $m(x) = \frac{5}{x^5} - \frac{3}{5x^7} $

\item $n(x) = \frac{1}{x^8} + \frac{2}{4x^4} $

\item $p(x) = \frac{6}{x^4} + \frac{4}{2x^6} $
\end{multicols}
\end{enumerate}

\item Calcule las siguientes derivadas

\begin{enumerate}
\begin{multicols}{3}
\item $g(x) = \frac{\sqrt{5}}{5}(x^4 - x^3)$

\item $h(x) = \frac{\sqrt{4}}{3}(x^5 - x^4)$

\item $k(x) = \frac{\sqrt{7}}{4}(x^3 - x^2)$

\item $m(x) = \frac{\sqrt{3}}{5}(x^3 - x^4)$

\item $n(x) = \frac{\sqrt{2}}{3}(x^3 - x^9)$

\item $p(x) = \frac{\sqrt{4}}{4}(x^3 - x^6)$

\end{multicols}
\end{enumerate}

\item Calcule las siguientes derivadas

\begin{enumerate}
\begin{multicols}{3}

\item $g(x) = (4x^3 + 3x^2)^3$

\item $h(x) = (3x^4 + 6x^3)^2$

\item $k(x) = \left(\frac{4x^3}{2} + \frac{3x^2}{2}\right)^2$

\item $m(x) = (4x^3 + 3x^6)^2$

\item $n(x) = (2x^8 + x^4)^2$

\item $p(x) = (5x^6 + x^4)^2$


\end{multicols}
\end{enumerate}

\item Calcule las siguientes derivadas

\begin{enumerate}
\begin{multicols}{3}

\item $g(x) = \frac{4x^2 - 2x + 8}{4x + 8}$

\item $h(x) = \frac{2x^2 + 6x + 12}{3x + 12}$
\item $k(x) = \frac{2x^2 - 4x - 8}{6x - 8}$
\item $m(x) = \frac{2x^2 + 3x + 6}{5x + 3}$
\item $n(x) = \frac{2x^3 + 4x^2 + 6x + 8}{4x^2 - 3x + 8}$
\item $p(x) = \frac{2x^2 + \frac{1}{2}x + 3}{2x + \frac{1}{2}}$
\end{multicols}
\end{enumerate}

\item Calcule las siguientes derivadas

\begin{enumerate}
\begin{multicols}{3}


\item $g(x) = \frac{x^2 - 4}{x^2 + 4}$
\item $h(x) = \frac{x^2 - 16}{x^2 + 16}$
\item $k(x) = \frac{x^2 + 1}{x^2 - 1}$
\item $m(x) = \frac{x^2 - 25}{x^2 + 25}$
\item $n(x) = \frac{x^3 - 8}{x^3 + 8}$

\item $p(x) = \frac{x^2 + \frac{1}{2}}{x^2 - \frac{1}{2}}$
\end{multicols}
\end{enumerate}

\item Calcule las siguientes derivadas

\begin{enumerate}
\begin{multicols}{3}
\item $g(x) = \frac{3x+2}{x+4}(4x-3)$

\item $h(x) = \frac{-x+6}{3x+6}(5x-1)$

\item $k(x) = \frac{12x-1}{7x+2}(3x+4)$

\item $m(x) = \frac{-3x+4}{6x+3}(4x-\sqrt{2})$

\item $n(x) = \frac{7x+6}{4x+7}(2x^2-1)$

\item $p(x) = \frac{-6x-5}{2x+1}\left(\frac{3x}{2}+\frac{1}{3}\right)$

\end{multicols}
\end{enumerate}

\end{enumerate}



