---
title: "Cálculo Diferencial: Ejercicios de Límites"
author: "Carlos Ernesto Martinez"
date: "28-Septiembre-2023"
documentclass: article
output:
  pdf_document:
    toc: no  # Cambiado a "no" para eliminar la tabla de contenidos
    number_sections: no
header-includes:
  - \usepackage{multicol}
  - \usepackage{fancyhdr}
  - \usepackage[document]{ragged2e}
  - \pagestyle{fancy}
  - \fancyhf{}
  - \fancyfoot[C]{\thepage}
  - \fancyfoot[L]{\ifodd\value{page}\textit{\small Ejercicios de Límites}\else\textit{\small Carlos E Martínez-Rodríguez}\fi}
  - \fancyfoot[R]{\ifodd\value{page}\textit{\small Carlos E Martínez-Rodríguez}\else\textit{\small Ejercicios de Límites}\fi}
  - \usepackage[left=2cm,right=2cm,top=2cm,bottom=2cm]{geometry}
  - \fancyhead[LE,RO]{\nouppercase{\rightmark}}
  - \fancyhead[LO,RE]{\nouppercase{\leftmark}}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

\begin{enumerate}

\item Resolver los siguientes lìmites


\begin{enumerate}
\begin{multicols}{3}
\item $\lim_{x\to 2}\frac{x^2 - 1}{x-1}$

\item $\lim_{x\to -3}\frac{2x+5}{x+3}$

\item $\lim_{x\to 1}\frac{3x^2 - 4x - 3}{x-1}$

\item $\lim_{x\to 0}\frac{2x^2 + 3x}{x}$

\item $\lim_{x\to -1}\frac{x^3 - 1}{x^2 - 1}$

\item $\lim_{x\to 3}\frac{x^2 + 2x - 3}{x-3}$

\item $\lim_{x\to -2}\frac{3x+4}{x+2}$

\item $\lim_{x\to 2}\frac{x^3 - 2x^2 - x + 2}{x-2}$

\item $\lim_{x\to -4}\frac{2x^2 - 9x - 5}{x+4}$
\end{multicols}
\end{enumerate}


\item Resolver los siguientes lìmites


\begin{enumerate}
\begin{multicols}{3}

\item $\lim_{x\to 3}\frac{x}{x-3}$

\item $\lim_{x\to -2}\frac{x^2}{x+2}$

\item $\lim_{x\to 1}\frac{2x}{x-1}$

\item $\lim_{x\to -1}\frac{x^3}{x+1}$

\item $\lim_{x\to 5}\frac{4x}{x-5}$

\item $\lim_{x\to 0}\frac{x}{x-0}$

\item $\lim_{x\to 4}\frac{x^2}{x-4}$

\item $\lim_{x\to 2}\frac{3x}{x-2}$

\item $\lim_{x\to -3}\frac{x^3}{x+3}$
\end{multicols}
\end{enumerate}


\item Resolver los siguientes lìmites


\begin{enumerate}
\begin{multicols}{3}

\item $\lim_{x\to -2}\frac{3x}{4-x^2}$

\item $\lim_{x\to 1}\frac{x}{5-x^2}$

\item $\lim_{x\to 0}\frac{2x}{3-x^2}$

\item $\lim_{x\to -1}\frac{5x}{4-x^2}$

\item $\lim_{x\to 2}\frac{x}{x^2-5}$

\item $\lim_{x\to 3}\frac{4x}{5-x^2}$

\item $\lim_{x\to -1}\frac{2x}{x^2-9}$

\item $\lim_{x\to 0}\frac{3x}{x^2+1}$

\item $\lim_{x\to -1}\frac{6x}{x^2-4}$
\end{multicols}
\end{enumerate}

\item Resolver los siguientes lìmites


\begin{enumerate}
\begin{multicols}{3}

\item $\lim_{x\to -1}\frac{x+3}{x^2-1}$

\item $\lim_{x\to 2}\frac{x+4}{x^2-4}$

\item $\lim_{x\to 4}\frac{x+1}{x^2-16}$

\item $\lim_{x\to 2}\frac{x+5}{x^2-4}$

\item $\lim_{x\to 6}\frac{x+6}{x^2-36}$

\item $\lim_{x\to 5}\frac{x+4}{x^2-25}$

\item $\lim_{x\to 3}\frac{x+2}{x^2-9}$

\item $\lim_{x\to 8}\frac{x+5}{x^2-64}$

\item $\lim_{x\to 9}\frac{x+6}{x^2-81}$
\end{multicols}
\end{enumerate}

\item Resolver los siguientes lìmites


\begin{enumerate}
\begin{multicols}{3}

\item $\lim_{x\to 2}\frac{\sqrt{4+x^2}}{x}$

\item $\lim_{x\to 1}\frac{\sqrt{1+x^2}}{x}$

\item $\lim_{x\to 0}\frac{\sqrt{3+x^2}}{x}$

\item $\lim_{x\to -1}\frac{\sqrt{2+x^2}}{x}$

\item $\lim_{x\to 4}\frac{\sqrt{5+x^2}}{x}$

\item $\lim_{x\to 3}\frac{\sqrt{9+x^2}}{x}$

\item $\lim_{x\to 1}\frac{\sqrt{1+x^2}}{x}$

\item $\lim_{x\to 0}\frac{\sqrt{16+x^2}}{x}$

\item $\lim_{x\to -2}\frac{\sqrt{4+x^2}}{x}$
\end{multicols}
\end{enumerate}

\item Resolver los siguientes lìmites


\begin{enumerate}
\begin{multicols}{3}

\item $\lim_{x\to 2}\frac{\sqrt{x^2-4}}{x-2}$

\item $\lim_{x\to 4}\frac{\sqrt{x^2-16}}{x-4}$

\item $\lim_{x\to 1}\frac{\sqrt{x^2-1}}{x-1}$

\item $\lim_{x\to 5}\frac{\sqrt{x^2-25}}{x-5}$

\item $\lim_{x\to -2}\frac{\sqrt{x^2-4}}{x+2}$

\item $\lim_{x\to 3}\frac{\sqrt{x^2-9}}{x-3}$

\item $\lim_{x\to 4}\frac{\sqrt{x^2-16}}{x-4}$

\item $\lim_{x\to 1}\frac{\sqrt{x^2-1}}{x-1}$

\item $\lim_{x\to 5}\frac{\sqrt{x^2-25}}{x-5}$
\end{multicols}
\end{enumerate}


\item Resolver los siguientes lìmites


\begin{enumerate}
\begin{multicols}{3}
\item $\lim_{x\to 0}\left(\frac{1}{x^2}-\frac{1}{x^3}\right)$

\item $\lim_{x\to 0}\left(\frac{1}{x}-\frac{1}{x^3}\right)$

\item $\lim_{x\to 0}\left(\frac{1}{x^2}-\frac{1}{x^4}\right)$

\item $\lim_{x\to 0}\left(\frac{1}{x}-\frac{1}{x^4}\right)$

\item $\lim_{x\to 0}\left(\frac{1}{x^3}-\frac{1}{x^4}\right)$

\item $\lim_{x\to 0}\left(\frac{1}{x}-\frac{1}{x^2}\right)$

\item $\lim_{x\to 0}\left(\frac{1}{x^2}-\frac{1}{x^4}\right)$

\item $\lim_{x\to 0}\left(\frac{1}{x}-\frac{1}{x^4}\right)$

\item $\lim_{x\to 0}\left(\frac{1}{x^3}-\frac{1}{x^4}\right)$

\end{multicols}
\end{enumerate}

\item Resolver los siguientes lìmites


\begin{enumerate}
\begin{multicols}{3}

\item $\lim_{x\to 0}\frac{3x^2-2x^3}{4x^3+x^2}$

\item $\lim_{x\to 0}\frac{x^3-2x^2}{3x^4-5x^2}$

\item $\lim_{x\to 0}\frac{x^4-4x^3}{5x^5-2x^2}$

\item $\lim_{x\to 0}\frac{6x^3-5x^4}{x^2-3x^5}$

\item $\lim_{x\to 0}\frac{x^3-6x^4}{2x^5+4x^2}$

\item $\lim_{x\to 0}\frac{x^3-2x^4}{3x^5-5x^2}$

\item $\lim_{x\to 0}\frac{x^4-4x^5}{5x^6-2x^3}$

\item $\lim_{x\to 0}\frac{6x^3-5x^4}{x^2-3x^6}$

\item $\lim_{x\to 0}\frac{x^4-6x^5}{2x^6+4x^3}$
\end{multicols}
\end{enumerate}

\item Resolver los siguientes lìmites


\begin{enumerate}
\begin{multicols}{3}

\item $\lim_{x\to 2}\left(\frac{1}{x}-\frac{3}{x^2-4}\right)$

\item $\lim_{x\to 3}\left(\frac{2}{x+1}-\frac{4}{x^2-9}\right)$

\item $\lim_{x\to 1}\left(\frac{5}{x-2}-\frac{2}{x^2-1}\right)$

\item $\lim_{x\to -2}\left(\frac{1}{x+2}-\frac{2}{x^2-1}\right)$

\item $\lim_{x\to -1}\left(\frac{4}{x+1}-\frac{1}{x^2-4}\right)$

\item $\lim_{x\to -3}\left(\frac{2}{x+1}-\frac{4}{x^2-9}\right)$

\item $\lim_{x\to 2}\left(\frac{5}{x-2}-\frac{2}{x^2-1}\right)$

\item $\lim_{x\to -2}\left(\frac{1}{x+2}-\frac{2}{x^2-1}\right)$

\item $\lim_{x\to -1}\left(\frac{4}{x+1}-\frac{1}{x^2-4}\right)$
\end{multicols}
\end{enumerate}

\item Resolver los siguientes lìmites


\begin{enumerate}
\begin{multicols}{3}


\item $\lim_{x\to 1}\frac{x^3+5x^2+6x}{x^2-3x+2}$

\item $\lim_{x\to 3}\frac{x^3+8x^2+12x}{x^2-4x+3}$

\item $\lim_{x\to 5}\frac{x^3+4x^2+3x}{x^2-2x-15}$

\item $\lim_{x\to 2}\frac{x^3+10x^2+25x}{x^2-5x+6}$

\item $\lim_{x\to 1}\frac{x^3+7x^2+10x}{x^2-3x+2}$

\item $\lim_{x\to 3}\frac{x^3+8x^2+12x}{x^2-4x+3}$

\item $\lim_{x\to -3}\frac{x^3+4x^2+3x}{x^2-2x-15}$

\item $\lim_{x\to 2}\frac{x^3+10x^2+25x}{x^2-5x+6}$

\item $\lim_{x\to 2}\frac{x^3+7x^2+10x}{x^2-3x+2}$


\end{multicols}
\end{enumerate}

\item Resolver los siguientes lìmites


\begin{enumerate}
\begin{multicols}{3}


\item $\lim_{x\to -5}\frac{3}{x^2+7x+10}$

\item $\lim_{x\to 3}\frac{2}{x^2-6x+9}$

\item $\lim_{x\to -4}\frac{4}{x^2+9x+20}$

\item $\lim_{x\to 3}\frac{6}{x^2-0x+21}$

\item $\lim_{x\to -5}\frac{7}{x^2+5x}$

\item $\lim_{x\to 3}\frac{4}{x^2+4x-21}$

\item $\lim_{x\to 9}\frac{2}{x^2+8x-9}$

\item $\lim_{x\to 3}\frac{6}{x^2+8x-15}$

\item $\lim_{x\to 0}\frac{7}{x^2+3x}$
\end{multicols}
\end{enumerate}

\item Resolver los siguientes lìmites


\begin{enumerate}
\begin{multicols}{3}


\item $\lim_{x\to 4}\frac{\sqrt{x}-3}{x-4}$

\item $\lim_{x\to 2}\frac{\sqrt{x}-2}{x-4}$

\item $\lim_{x\to 4}\frac{\sqrt{x}-2}{x^2-16}$

\item $\lim_{x\to 1}\frac{\sqrt{x}+1}{x^2-1}$

\item $\lim_{x\to 4}\frac{\sqrt{x}+2}{x^3-64}$

\item $\lim_{x\to 4}\frac{\sqrt{x}-2}{x-4}$

\item $\lim_{x\to 4}\frac{\sqrt{x}-2}{x^2-16}$

\item $\lim_{x\to 4}\frac{\sqrt{x}+1}{x^2-12x+32}$

\item $\lim_{x\to 4}\frac{\sqrt{x}+2}{x^2-64}$
\end{multicols}
\end{enumerate}

\item Resolver los siguientes lìmites


\begin{enumerate}
\begin{multicols}{3}


\item $\lim_{x\to -2}\frac{x^2+6x+9}{x+2}$

\item $\lim_{x\to 1}\frac{x^2+3x+2}{x-1}$

\item $\lim_{x\to -1}\frac{x^2+5x+6}{x+1}$

\item $\lim_{x\to -4}\frac{x^2+2x+1}{x+4}$

\item $\lim_{x\to -2}\frac{x^2+7x+12}{x+2}$

\item $\lim_{x\to 1}\frac{x^2+3x+2}{x-1}$

\item $\lim_{x\to -1}\frac{x^2+5x+6}{x+1}$

\item $\lim_{x\to -4}\frac{x^2+2x+1}{x+4}$

\item $\lim_{x\to -2}\frac{x^2+7x+12}{x+2}$
\end{multicols}
\end{enumerate}

\item Resolver los siguientes lìmites


\begin{enumerate}
\begin{multicols}{3}


\item $\lim_{x\to 16}\frac{x-11}{\sqrt{x}-4}$

\item $\lim_{x\to 4}\frac{x-8}{\sqrt{x}-2}$

\item $\lim_{x\to 1}\frac{x-10}{\sqrt{x}+1}$

\item $\lim_{x\to 1}\frac{x-7}{\sqrt{x}+4}$

\item $\lim_{x\to 25}\frac{x-12}{\sqrt{x}-5}$

\item $\lim_{x\to 4}\frac{x-8}{\sqrt{x}-2}$

\item $\lim_{x\to 1}\frac{x-10}{\sqrt{x}+1}$

\item $\lim_{x\to 9}\frac{x-7}{\sqrt{x}+4}$

\item $\lim_{x\to 25}\frac{x-12}{\sqrt{x}-5}$
\end{multicols}
\end{enumerate}

\item Resolver los siguientes lìmites


\begin{enumerate}
\begin{multicols}{3}


\item $\lim_{x\to 5}\frac{x-4}{\sqrt{x-4}-1}$

\item $\lim_{x\to 15}\frac{x-6}{\sqrt{x-6}-3}$

\item $\lim_{x\to 3}\frac{x-3}{\sqrt{x-3}}$

\item $\lim_{x\to 23}\frac{x-7}{\sqrt{x-7}-4}$

\item $\lim_{x\to 4}\frac{x-2}{\sqrt{x-2}-1}$

\item $\lim_{x\to 15}\frac{x-6}{\sqrt{x-6}-3}$

\item $\lim_{x\to 3}\frac{x-3}{\sqrt{x-3}}$

\item $\lim_{x\to 23}\frac{x-7}{\sqrt{x-7}-4}$

\item $\lim_{x\to 3}\frac{x-2}{\sqrt{x-2}-1}$
\end{multicols}
\end{enumerate}

\item Resolver los siguientes lìmites


\begin{enumerate}
\begin{multicols}{3}


\item $\lim_{x\to 1}\frac{\sqrt{x+5}-2}{x-1}$

\item $\lim_{x\to 2}\frac{\sqrt{x+3}-4}{x-2}$

\item $\lim_{x\to 11}\frac{\sqrt{x+2}-5}{x-11}$

\item $\lim_{x\to 7}\frac{\sqrt{x+6}-1}{x-7}$

\item $\lim_{x\to 4}\frac{\sqrt{x+1}-6}{x-4}$

\item $\lim_{x\to 6}\frac{\sqrt{x+3}-4}{x-6}$

\item $\lim_{x\to 12}\frac{\sqrt{x+2}-5}{x-12}$

\item $\lim_{x\to 3}\frac{\sqrt{x+6}-1}{x-3}$

\item $\lim_{x\to 5}\frac{\sqrt{x+1}-6}{x-5}$
\end{multicols}
\end{enumerate}

\item Resolver los siguientes lìmites


\begin{enumerate}
\begin{multicols}{3}


\item $\lim_{x\to 5}\frac{x+2}{x-1}$

\item $\lim_{x\to -3}\frac{2x+5}{x+3}$

\item $\lim_{x\to 1}\frac{3x^2 - 4x - 3}{x-1}$

\item $\lim_{x\to 0}\frac{2x^2 + 3x}{x}$

\item $\lim_{x\to -1}\frac{x^3 - 1}{x^2 - 1}$

\item $\lim_{x\to 2}\frac{x^2 + 2x - 3}{x-2}$

\item $\lim_{x\to -4}\frac{3x+4}{x+4}$

\item $\lim_{x\to 2}\frac{4x^2 - 5x - 6}{x-2}$

\item $\lim_{x\to 0}\frac{5x^2 + 6x}{x}$

\item $\lim_{x\to 1}\frac{x^3 - 3x^2 + 2x}{x-1}$


\end{multicols}
\end{enumerate}


\end{enumerate}