---
title: "Cálculo Diferencial: Ejercicios de Derivadas (Regla de la Cadena)"
author: "Carlos Ernesto Martinez"
date: "13 de Octubre de 2023"
documentclass: article
output:
  pdf_document:
    toc: no  # Cambiado a "no" para eliminar la tabla de contenidos
    number_sections: no
header-includes:
  - \usepackage{multicol}
  - \usepackage{fancyhdr}
  - \usepackage[document]{ragged2e}
  - \pagestyle{fancy}
  - \fancyhf{}
  - \fancyfoot[C]{\thepage}
  - \fancyfoot[L]{\ifodd\value{page}\textit{\small Ejercicios de Derivadas (Regla de la Cadena)}\else\textit{\small Carlos E Martínez-Rodríguez}\fi}
  - \fancyfoot[R]{\ifodd\value{page}\textit{\small Carlos E Martínez-Rodríguez}\else\textit{\small Ejercicios de Derivadas (Regla de la Cadena)}\fi}
  - \usepackage[left=2cm,right=2cm,top=2cm,bottom=2cm]{geometry}
  - \fancyhead[LE,RO]{\nouppercase{\rightmark}}
  - \fancyhead[LO,RE]{\nouppercase{\leftmark}}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

\begin{enumerate}

\item Calcula las siguientes derivadas:

\begin{multicols}{2}
\begin{enumerate}

\item $f(x) = (2x^2 + 3x + 1)^4$
\item $f(x) = (5x^2 - 2x + 7)^2$
\item $f(x) = (-3x^2 + 4x - 6)^3$
\item $f(x) = (4x^2 + 2x - 9)^5$
\item $f(x) = (6x^2 - 7x + 2)^2$

\end{enumerate}
\end{multicols}


\item Calcula las siguientes derivadas:

\begin{multicols}{2}
\begin{enumerate}

\item $f(x) = \sin(2x^2 + 3x + 1)$
\item $f(x) = \cos(4x^2 - 2x^4 + 7)$
\item $f(x) = \tan(x^3 - 4x^2 + 6x+1)$
\item $f(x) = \csc(5x^5 + 2x^4 - 3x-5)$
\item $f(x) = \sec(6x^2 - 7x^2 + 2x+3)$
\item $f(x) = \cot(2x^9 + 5x^4 - 4x-4)$

\end{enumerate}
\end{multicols}

\item Calcula las siguientes derivadas:

\begin{multicols}{2}
\begin{enumerate}

\item $f(x) = \tan(\sin x)$
\item $f(x) = \cos^4(5x^3)$
\item  $f(x) = \sin^2(\cos x)$
\item  $f(x) = \cos(\tan x)$
\item  $f(x) = \cos^3(\cos x)$
\item  $f(x) = \sin(\cos x)$

\end{enumerate}
\end{multicols}

\item Calcula las siguientes derivadas:

\begin{multicols}{2}
\begin{enumerate}

\item $f(x) = 4\cos(3x) - 5\sin(7x)$
\item $f(x) = 3\sin(2x) + 2\cos(4x)$
\item $f(x) = 5\sin(6x) + \cos(5x)$
\item $f(x) = 2\sin(2x) - 6\sin(3x)$
\item $f(x) = 3\cos(4x) - 4\cos(7x)$
\item $f(x) = 5\sin(3x) + 2\cos(2x)$

\end{enumerate}
\end{multicols}

\item Calcula las siguientes derivadas:

\begin{multicols}{2}
\begin{enumerate}

\item  $f(x) = 3\cos^2(x)\sin^6(x)$
\item  $f(x) = 5\sin^5(x)\cos^4(x)$
\item  $f(x) = 2\sin^3(x)\cos(x)$
\item  $f(x) = 6\cos^4(x)\sin^5(x)$
\item  $f(x) = \sin^2(x)\cos^8(x)$
\item  $f(x) = 4\cos^5(x)\sin^3(x)$
\end{enumerate}
\end{multicols}

\item Calcula las siguientes derivadas:

\begin{multicols}{2}
\begin{enumerate}

\item $f(x) = [(5x^3 + 2x^2 - 4x + 3)^5(x^3 - 2x^2 + 2x)^5]$
\item  $f(x) = [(3x^3 + 4x^2 - 2x + 1)^5(x^3 - x^2 + 2x)^5]$
\item  $f(x) = [(6x^3 - x^2 + 2x + 2)^5(x^3 + 2x^2 - 3x + 4)^5]$
\item  $f(x) = [(4x^3 - x^2 - 3x + 2)^5(x^3 - 4x^2 + 3x + 1)^5]$
\item  $f(x) = [(2x^3 + 3x^2 - 2x + 5)^5(x^3 - 2x^2 - x + 2)^5]$
\item  $f(x) = [(5x^3 - x^2 + 2x - 1)^5(x^3 - x^2 + 3x - 2)^5]$

\end{enumerate}
\end{multicols}


\end{enumerate}


