---
title: "Cálculo Diferencial: Ejercicios de Derivadas (Regla de la Cadena-Segunda Parte)"
author: "Carlos Ernesto Martinez"
date: "13 de Octubre de 2023"
documentclass: article
output:
  pdf_document:
    toc: no  # Cambiado a "no" para eliminar la tabla de contenidos
    number_sections: no
header-includes:
  - \usepackage{multicol}
  - \usepackage{fancyhdr}
  - \usepackage[document]{ragged2e}
  - \pagestyle{fancy}
  - \fancyhf{}
  - \fancyfoot[C]{\thepage}
  - \fancyfoot[L]{\ifodd\value{page}\textit{\small Ejercicios de Derivadas (Regla de la Cadena-Segunda Parte)}\else\textit{\small Carlos E Martínez-Rodríguez}\fi}
  - \fancyfoot[R]{\ifodd\value{page}\textit{\small Carlos E Martínez-Rodríguez}\else\textit{\small Ejercicios de Derivadas (Regla de la Cadena-Segunda Parte)}\fi}
  - \usepackage[left=2cm,right=2cm,top=2cm,bottom=2cm]{geometry}
  - \fancyhead[LE,RO]{\nouppercase{\rightmark}}
  - \fancyhead[LO,RE]{\nouppercase{\leftmark}}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

\begin{enumerate}
\item Calcula las siguientes derivadas:\footnote{Mientras que la física y las matemáticas nos pueden decir cómo comenzó el universo, no son muy útiles en predecir el comportamiento humano porque hay muchas ecuaciones que resolver. – Stephen Hawking}

\begin{multicols}{2}
\begin{enumerate}

\item $f(x) = [(5x^3 + 2x^2 - 4x + 3)^6(x^3 - 2x^2 + 2x)^3]$
\item  $f(x) = [(3x^3 + 4x^2 - 2x + 1)^3(x^3 - x^2 + 2x)^4]$
\item  $f(x) = [(6x^3 - x^2 + 2x + 2)^7(x^3 + 2x^2 - 3x + 4)^5]$
\item  $f(x) = [(4x^3 - x^2 - 3x + 2)^2(x^3 - 4x^2 + 3x + 1)^4]$
\item  $f(x) = [(2x^3 + 3x^2 - 2x + 5)^4(x^3 - 2x^2 - x + 2)^3]$
\item  $f(x) = [(5x^3 - x^2 + 2x - 1)^3(x^3 - x^2 + 3x - 2)^2]$

\end{enumerate}
\end{multicols}

\item Calcula las siguientes derivadas:

\begin{multicols}{2}
\begin{enumerate}

\item  $f(x) = 4\sqrt[3]{x^2}$
\item  $f(x) = \sqrt{4\sin^2x+9\cos^2 x}$
\item  $f(x) = \frac{1}{\sqrt{25-y^2}}$
\item  $f(x) = 4x^{1/2}+5x^{-1/2}$
\item  $f(x) = \sqrt{4x^2-1}$
\item  $f(x) = (5-2x^2)^{-1/2}$
\end{enumerate}
\end{multicols}

\item Calcula las siguientes derivadas:

\begin{multicols}{2}
\begin{enumerate}

\item $f(x) = 2\cos\sqrt{x}$
\item  $f(x) = 4\sec\sqrt{x}$
\item  $f(x) = \cot\sqrt{3x}$
\item  $f(x) = \sqrt{3\sin x}$
\item  $f(x) = \sqrt{\frac{\sin x}{1-\sin x}}$
\item  $f(x) = \sqrt{\frac{\cos x-1}{\sin x}}$
\end{enumerate}
\end{multicols}

\item Calcula las siguientes derivadas
\begin{multicols}{2}
\begin{enumerate}

\item $f(x) = \frac{4}{x^2}-\frac{3}{x^4}$
\item $f(x) = \frac{x^2-4x+4}{x-1}$
\item $f(x) = (3x^2-4)(4x^3+x-1)$
\item $f(x) = \frac{x^3-}{x^3+1}$
\item $f(x) = 2x^{1/2}-\frac{1}{2}x^{-1/2}$
\item $f(x) = (x^4-x)^{-3}(5-x^2)^{-1}$
\item $f(x) = (x+1)\sin2x-3x\cos3x$
\item $f(x) = x^2\cos\frac{1}{x}$
\item $f(x) = \sin\cos\frac{1}{x}-\frac{1}{x}\sin x\cos x$
\item $f(x) = \tan2x\sec3x-2x\sec x \tan x$
\item $f(x) = (\frac{2x}{x+1})^2$
\item $f(x) = \sqrt\frac{x}{4-x^2}$
\item $f(x) = \frac{\tan x}{1+x}$

\end{enumerate}
\end{multicols}



\end{enumerate}


