---
title: "Cálculo Diferencial: Ejercicios de Derivadas (Segunda Parte)"
author: "Carlos Ernesto Martinez"
date: "28 de Septiembre de 2023"
documentclass: article
output:
  pdf_document:
    toc: no  # Cambiado a "no" para eliminar la tabla de contenidos
    number_sections: no
header-includes:
  - \usepackage{multicol}
  - \usepackage{fancyhdr}
  - \usepackage[document]{ragged2e}
  - \pagestyle{fancy}
  - \fancyhf{}
  - \fancyfoot[C]{\thepage}
  - \fancyfoot[L]{\ifodd\value{page}\textit{\small Ejercicios de Derivadas (Tercera Parte)}\else\textit{\small Carlos E Martínez-Rodríguez}\fi}
  - \fancyfoot[R]{\ifodd\value{page}\textit{\small Carlos E Martínez-Rodríguez}\else\textit{\small Ejercicios de Derivadas (Tercera Parte)}\fi}
  - \usepackage[left=2cm,right=2cm,top=2cm,bottom=2cm]{geometry}
  - \fancyhead[LE,RO]{\nouppercase{\rightmark}}
  - \fancyhead[LO,RE]{\nouppercase{\leftmark}}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

\begin{enumerate}

\item Calcula las siguientes derivadas de los órdenes indicados:

\begin{multicols}{2}
\begin{enumerate}

\item $D^4[\sin(x) \cos(x) + x^3]$

\item $D^3[\csc(x) \cot(x) + x^4]$

\item $D^3[\sec(x) \tan(x) + x^5]$

\item $D^4[\sin(x) \csc(x) + x^2 \cos(x)]$

\item $D^5[\tan(x) \sec(x) + x^3 \sin(x)]$



\end{enumerate}
\end{multicols}

\item Calcula las siguientes derivadas :

\begin{multicols}{2}
\begin{enumerate}


\item $D_x[x^3\sin x + 3x^2\cos x]$

\item $D_x[x\sin x + x\cos x]$

\item $D_x[3x^2\sin x + x^3\cos x]$

\item $D_x[2x^3\sin x + 4x^2\cos x]$

\item $D_x[x^4\sin x + 4x^3\cos x]$
\item $D_x[2x\sin x + x^2\cos x]$

\item $D_x[x^4\sin x + 5x^3\cos x]$

\item $D_x[4x^2\sin x + 2x\cos x]$

\item $D_x[6x^3\sin x + 3x\cos x]$

\item $D_x[x^5\sin x + x^2\cos x]$


\end{enumerate}
\end{multicols}


\item Calcula las siguientes derivadas :

\begin{multicols}{2}
\begin{enumerate}


\item $D_x[(x^3\sin x + 3x^2\cos x)(2x\sin x + x^2\cos x)]$

\item $D_x[(x\sin x + x\cos x)(x^4\sin x + 5x^3\cos x)]$

\item $D_x[(3x^2\sin x + x^3\cos x)(4x^2\sin x + 2x\cos x)]$

\item $D_x[(2x^3\sin x + 4x^2\cos x)(6x^3\sin x + 3x\cos x)]$

\item $D_x[(x^4\sin x + 4x^3\cos x)(x^5\sin x + x^2\cos x)]$

\end{enumerate}
\end{multicols}



\item Calcula las siguiente derivadas:
\begin{multicols}{2}
\begin{enumerate}


\item  $D_x[\frac{\tan(x) \sin(x)}{\cos(x) + 2}]$.

\item $D_x[\frac{\csc(x) \sin(x)}{3\cos(x) - 1}]$.

\item $D_x[\frac{\tan(x) \cos(x)}{\sec(x) + 5}]$.

\item $D_x[\frac{\cot(x) \sin(x)}{4\cos(x) - 3}]$.

\item $D_x[\frac{\sin(x) \sec(x)}{2\cos(x) - 1}]$

\end{enumerate}
\end{multicols}


\item Calcula las siguientes derivadas
\begin{multicols}{2}
\begin{enumerate}

\item  $D_x[\frac{\tan(x) + \sin(x)}{\cot(x) - \cos(x)}]$.

\item  $D_x[\frac{\csc(x) + \cos(x)}{\sec(x) - \tan(x)}]$.

\item  $D_x[\frac{\sin(x) + \cot(x)}{\csc(x) - \cos(x)}]$.

\item $D_x[\frac{\cos(x) + \sec(x)}{\tan(x) - \csc(x)}]$.

\item  $D_x[\frac{\sec(x) + \sin(x)}{\cot(x) - \csc(x)}]$.

\end{enumerate}
\end{multicols}

\end{enumerate}



